# Generated by Django 5.1 on 2024-08-22 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name": "Category"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
    ]
